services:
    frankenphp:
        build:
            context: .
        entrypoint: php artisan octane:frankenphp --workers=10
        ports:
            - "8000:8000"
        volumes:
            - .:/app
    npm_builder:
        image: node:24-alpine3.22
        volumes:
            - .:/app
        working_dir: /app
        # entrypoint: ["/bin/sh", "-c", "npm install && npm run build"]
    composer:
        image: composer:latest
        volumes:
            - .:/app
        working_dir: /app
